#ifndef LIBNABLA_VERSION_
#define LIBNABLA_VERSION_

#define LIBNABLA_MAJOR_VERSION (0)
#define LIBNABLA_MINOR_VERSION (1)
#define LIBNABLA_PATCH_VERSION (0)
#define LIBNABLA_VERSION "0.1.0"

#endif  // LIBNABLA_VERSION_
